#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(CDPATH= cd -- "$DEPLOY_DIR/.." && pwd)"
SITE_FILE="${1:-$SCRIPT_DIR/site.local}"

log() { printf '==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

prompt_value() {
  local name=$1 fallback=$2 value
  read -r -p "$name [$fallback]: " value
  printf '%s=%s\n' "$name" "${value:-$fallback}"
}

init_site() {
  local dest=${1:-$SCRIPT_DIR/site.local}
  [[ ! -e "$dest" ]] || die "$dest already exists"
  log "Creating $dest"
  {
    printf '# Generated by deploy/env/generate.sh --init. Contains deployment wiring only.\n\n'
    prompt_value APP_DIR /home/adamhoof/MOBv3
    prompt_value HOST_BIND_IP 10.0.0.149
    printf '\n'
    prompt_value GO_IMAGE docker.io/library/golang:1.26-alpine
    prompt_value ALPINE_IMAGE docker.io/library/alpine:3.20
    prompt_value MOSQUITTO_IMAGE docker.io/library/eclipse-mosquitto:2.1.2-alpine
    prompt_value TARGETARCH amd64
    printf '\n'
    prompt_value WORKDIR /app
    prompt_value CERT_DIR /home/adamhoof/MOBv3/certs
    prompt_value CREDENTIAL_DIR /home/adamhoof/MOBv3/deploy/credentials
    printf '\n'
    prompt_value MQTT_PROTOCOL tcps
    prompt_value MQTT_PORT 8883
    prompt_value CATALOG_HTTP_PORT 8443
    prompt_value PROXY_PORT 9100
    prompt_value USB_PRINTER /dev/usb/lp0
    printf '\n'
    prompt_value CATALOG_DB_PATH /data/catalog.db
    prompt_value CATALOG_IMPORT_ENDPOINT /catalog/import
    prompt_value MQTT_CATALOG_CLIENT_ID catalog_service
    prompt_value MQTT_TOPIC_REQUEST 'product/+/+'
    prompt_value QRPROXY_MQTT_CLIENT_ID qrproxy
    prompt_value QTERM_MQTT_TOPIC qterm/payments
  } >"$dest"
}

if [[ ${1:-} == "--init" ]]; then
  init_site "${2:-$SCRIPT_DIR/site.local}"
  exit 0
fi

[[ -f "$SCRIPT_DIR/site.example" ]] || die "missing $SCRIPT_DIR/site.example"
set -a
# shellcheck disable=SC1091
source "$SCRIPT_DIR/site.example"
if [[ -f "$SITE_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$SITE_FILE"
else
  log "No $SITE_FILE found; using site.example defaults"
fi
set +a

: "${APP_DIR:?}"
: "${HOST_BIND_IP:?}"
: "${GO_IMAGE:?}"
: "${ALPINE_IMAGE:?}"
: "${MOSQUITTO_IMAGE:?}"
: "${TARGETARCH:?}"
: "${WORKDIR:?}"
: "${CERT_DIR:?}"
: "${CREDENTIAL_DIR:?}"
: "${MQTT_PROTOCOL:?}"
: "${MQTT_PORT:?}"
: "${CATALOG_HTTP_PORT:?}"
: "${PROXY_PORT:?}"
: "${USB_PRINTER:?}"
: "${CATALOG_DB_PATH:?}"
: "${CATALOG_IMPORT_ENDPOINT:?}"
: "${MQTT_CATALOG_CLIENT_ID:?}"
: "${MQTT_TOPIC_REQUEST:?}"
: "${QRPROXY_MQTT_CLIENT_ID:?}"
: "${QTERM_MQTT_TOPIC:?}"

ENV_OUT="$ROOT_DIR/deploy/generated/env"
QUADLET_OUT="$ROOT_DIR/deploy/generated/quadlet"
SOURCE_DIR="$APP_DIR/source"
mkdir -p "$ENV_OUT" "$QUADLET_OUT"

cat >"$ENV_OUT/mosquitto.env" <<EOF
# Generated by deploy/env/generate.sh. Do not edit by hand.
EOF

cat >"$ENV_OUT/catalog.env" <<EOF
# Generated by deploy/env/generate.sh. Do not edit by hand.
CATALOG_DB_PATH=$CATALOG_DB_PATH
CATALOG_HTTP_HOST=0.0.0.0
CATALOG_HTTP_PORT=$CATALOG_HTTP_PORT
CATALOG_IMPORT_ENDPOINT=$CATALOG_IMPORT_ENDPOINT
MQTT_PROTOCOL=$MQTT_PROTOCOL
MQTT_HOST=mobv3_mosquitto_broker
MQTT_PORT=$MQTT_PORT
MQTT_CATALOG_CLIENT_ID=$MQTT_CATALOG_CLIENT_ID
MQTT_TOPIC_REQUEST=$MQTT_TOPIC_REQUEST
TLS_CA_PATH=$WORKDIR/certs/ca.crt
CATALOG_TLS_SERVER_CERT_PATH=$WORKDIR/certs/catalog_server.crt
CATALOG_TLS_SERVER_KEY_PATH=/run/secrets/mobv3_catalog_server_key
TLS_CLIENT_CERT_PATH=$WORKDIR/certs/client.crt
TLS_CLIENT_KEY_PATH=/run/secrets/mobv3_client_key
XDG_CACHE_HOME=/data/.cache
EOF

cat >"$ENV_OUT/qrproxy.env" <<EOF
# Generated by deploy/env/generate.sh. Do not edit by hand.
PROXY_IP=0.0.0.0
PROXY_PORT=$PROXY_PORT
USB_PRINTER=$USB_PRINTER
MQTT_PROTOCOL=$MQTT_PROTOCOL
MQTT_HOST=mobv3_mosquitto_broker
MQTT_PORT=$MQTT_PORT
QRPROXY_MQTT_CLIENT_ID=$QRPROXY_MQTT_CLIENT_ID
QTERM_MQTT_TOPIC=$QTERM_MQTT_TOPIC
TLS_CA_PATH=$WORKDIR/certs/ca.crt
TLS_CLIENT_CERT_PATH=$WORKDIR/certs/client.crt
TLS_CLIENT_KEY_PATH=/run/secrets/mobv3_client_key
EOF

cat >"$QUADLET_OUT/mobv3.network" <<EOF
[Network]
NetworkName=mobv3_network
EOF

cat >"$QUADLET_OUT/mobv3-catalog.build" <<EOF
[Build]
ImageTag=localhost/mobv3-catalog_service:latest
File=$SOURCE_DIR/cmd/catalog_service/Containerfile
SetWorkingDirectory=$SOURCE_DIR
BuildArg=GO_IMAGE=$GO_IMAGE
BuildArg=ALPINE_IMAGE=$ALPINE_IMAGE
BuildArg=TARGETARCH=$TARGETARCH
BuildArg=WORKDIR=$WORKDIR
EOF

cat >"$QUADLET_OUT/mobv3-qrproxy.build" <<EOF
[Build]
ImageTag=localhost/mobv3-qrproxy:latest
File=$SOURCE_DIR/cmd/qrproxy/Containerfile
SetWorkingDirectory=$SOURCE_DIR
BuildArg=GO_IMAGE=$GO_IMAGE
BuildArg=TARGETARCH=$TARGETARCH
EOF

cat >"$QUADLET_OUT/mobv3-mosquitto.container" <<EOF
[Unit]
Description=MOBv3 Mosquitto broker
Wants=network-online.target
After=network-online.target

[Container]
ContainerName=mobv3_mosquitto_broker
Image=$MOSQUITTO_IMAGE
User=1883:0
EnvironmentFile=$APP_DIR/deploy/generated/env/mosquitto.env
Network=mobv3.network
PublishPort=$HOST_BIND_IP:$MQTT_PORT:$MQTT_PORT
Volume=$APP_DIR/deploy/mosquitto:/mosquitto/config:ro,Z
Volume=mobv3_mosquitto_data:/mosquitto/data
Volume=mobv3_mosquitto_log:/mosquitto/log
Volume=$CERT_DIR/mosquitto_server.crt:/mosquitto/certs/mosquitto_server.crt:ro,Z
Volume=$CERT_DIR/ca.crt:/mosquitto/certs/ca.crt:ro,Z
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_mosquitto_server_key:/run/secrets/mobv3_mosquitto_server_key:ro

[Service]
LoadCredentialEncrypted=mobv3_mosquitto_server_key:$CREDENTIAL_DIR/mobv3_mosquitto_server_key.cred
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF

cat >"$QUADLET_OUT/mobv3-catalog.container" <<EOF
[Unit]
Description=MOBv3 catalog service
Wants=network-online.target mobv3-mosquitto.service
After=network-online.target mobv3-mosquitto.service

[Container]
ContainerName=mobv3_catalog_service
Image=mobv3-catalog.build
User=1000:0
EnvironmentFile=$APP_DIR/deploy/generated/env/catalog.env
Network=mobv3.network
PublishPort=$HOST_BIND_IP:$CATALOG_HTTP_PORT:$CATALOG_HTTP_PORT
Volume=mobv3_catalog_data:/data
Volume=$CERT_DIR/catalog_server.crt:$WORKDIR/certs/catalog_server.crt:ro,Z
Volume=$CERT_DIR/ca.crt:$WORKDIR/certs/ca.crt:ro,Z
Volume=$CERT_DIR/client.crt:$WORKDIR/certs/client.crt:ro,Z
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_catalog_server_key:/run/secrets/mobv3_catalog_server_key:ro
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_client_key:/run/secrets/mobv3_client_key:ro

[Service]
LoadCredentialEncrypted=mobv3_catalog_server_key:$CREDENTIAL_DIR/mobv3_catalog_server_key.cred
LoadCredentialEncrypted=mobv3_client_key:$CREDENTIAL_DIR/mobv3_client_key.cred
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF

cat >"$QUADLET_OUT/mobv3-qrproxy.container" <<EOF
[Unit]
Description=MOBv3 QRProxy
Wants=network-online.target mobv3-mosquitto.service
After=network-online.target mobv3-mosquitto.service

[Container]
ContainerName=mobv3_qrproxy
Image=mobv3-qrproxy.build
User=0:0
GroupAdd=keep-groups
SecurityLabelDisable=true
EnvironmentFile=$APP_DIR/deploy/generated/env/qrproxy.env
Network=mobv3.network
PublishPort=$HOST_BIND_IP:$PROXY_PORT:$PROXY_PORT
Volume=$CERT_DIR/ca.crt:$WORKDIR/certs/ca.crt:ro,Z
Volume=$CERT_DIR/client.crt:$WORKDIR/certs/client.crt:ro,Z
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_client_key:/run/secrets/mobv3_client_key:ro
AddDevice=$USB_PRINTER:$USB_PRINTER

[Service]
LoadCredentialEncrypted=mobv3_client_key:$CREDENTIAL_DIR/mobv3_client_key.cred
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF

log "Generated env files in $ENV_OUT"
log "Generated Quadlet files in $QUADLET_OUT"
