#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/../lib/config.sh"

load_config machine
require_machine_config
require_vars APP_DIR HOST_BIND_IP WORKDIR CERT_DIR CREDENTIAL_DIR GO_IMAGE ALPINE_IMAGE TARGETARCH CATALOG_DB_PATH CATALOG_HTTP_PORT CATALOG_IMPORT_ENDPOINT MQTT_PROTOCOL MQTT_PORT MQTT_CATALOG_CLIENT_ID MQTT_TOPIC_REQUEST
prepare_outputs

source_dir="$APP_DIR/source"

cat >"$env_out/catalog.env" <<EOF
# Generated by deploy/services/catalog.sh. Do not edit by hand.
CATALOG_DB_PATH=$CATALOG_DB_PATH
CATALOG_HTTP_HOST=0.0.0.0
CATALOG_HTTP_PORT=$CATALOG_HTTP_PORT
CATALOG_IMPORT_ENDPOINT=$CATALOG_IMPORT_ENDPOINT
MQTT_PROTOCOL=$MQTT_PROTOCOL
MQTT_HOST=mobv3_mosquitto_broker
MQTT_PORT=$MQTT_PORT
MQTT_CATALOG_CLIENT_ID=$MQTT_CATALOG_CLIENT_ID
MQTT_TOPIC_REQUEST=$MQTT_TOPIC_REQUEST
TLS_CA_PATH=$WORKDIR/certs/ca.crt
CATALOG_TLS_SERVER_CERT_PATH=$WORKDIR/certs/catalog_server.crt
CATALOG_TLS_SERVER_KEY_PATH=/run/secrets/mobv3_catalog_server_key
TLS_CLIENT_CERT_PATH=$WORKDIR/certs/client.crt
TLS_CLIENT_KEY_PATH=/run/secrets/mobv3_client_key
XDG_CACHE_HOME=/data/.cache
EOF

cat >"$quadlet_out/mobv3-catalog.build" <<EOF
[Build]
ImageTag=localhost/mobv3-catalog_service:latest
File=$source_dir/cmd/catalog_service/Containerfile
SetWorkingDirectory=$source_dir
BuildArg=GO_IMAGE=$GO_IMAGE
BuildArg=ALPINE_IMAGE=$ALPINE_IMAGE
BuildArg=TARGETARCH=$TARGETARCH
BuildArg=WORKDIR=$WORKDIR
EOF

cat >"$quadlet_out/mobv3-catalog.container" <<EOF
[Unit]
Description=MOBv3 catalog service
Wants=network-online.target mobv3-mosquitto.service
After=network-online.target mobv3-mosquitto.service

[Container]
ContainerName=mobv3_catalog_service
Image=mobv3-catalog.build
User=1000:0
EnvironmentFile=$APP_DIR/deploy/generated/env/catalog.env
Network=mobv3.network
PublishPort=$HOST_BIND_IP:$CATALOG_HTTP_PORT:$CATALOG_HTTP_PORT
Volume=mobv3_catalog_data:/data
Volume=$CERT_DIR/catalog_server.crt:$WORKDIR/certs/catalog_server.crt:ro,Z
Volume=$CERT_DIR/ca.crt:$WORKDIR/certs/ca.crt:ro,Z
Volume=$CERT_DIR/client.crt:$WORKDIR/certs/client.crt:ro,Z
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_catalog_server_key:/run/secrets/mobv3_catalog_server_key:ro
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_client_key:/run/secrets/mobv3_client_key:ro

[Service]
LoadCredentialEncrypted=mobv3_catalog_server_key:$CREDENTIAL_DIR/mobv3_catalog_server_key.cred
LoadCredentialEncrypted=mobv3_client_key:$CREDENTIAL_DIR/mobv3_client_key.cred
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF

log "Generated catalog env and Quadlet units"
