#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/../lib/config.sh"

load_config machine
require_machine_config
require_vars APP_DIR HOST_BIND_IP CERT_DIR CREDENTIAL_DIR MOSQUITTO_IMAGE MQTT_PORT
prepare_outputs

cat >"$env_out/mosquitto.env" <<EOF
# Generated by deploy/services/mosquitto.sh. Do not edit by hand.
EOF

cat >"$quadlet_out/mobv3-mosquitto.container" <<EOF
[Unit]
Description=MOBv3 Mosquitto broker
Wants=network-online.target
After=network-online.target

[Container]
ContainerName=mobv3_mosquitto_broker
Image=$MOSQUITTO_IMAGE
User=1883:0
EnvironmentFile=$APP_DIR/deploy/generated/env/mosquitto.env
Network=mobv3.network
PublishPort=$HOST_BIND_IP:$MQTT_PORT:$MQTT_PORT
Volume=$APP_DIR/deploy/mosquitto:/mosquitto/config:ro,Z
Volume=mobv3_mosquitto_data:/mosquitto/data
Volume=mobv3_mosquitto_log:/mosquitto/log
Volume=$CERT_DIR/mosquitto_server.crt:/mosquitto/certs/mosquitto_server.crt:ro,Z
Volume=$CERT_DIR/ca.crt:/mosquitto/certs/ca.crt:ro,Z
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_mosquitto_server_key:/run/secrets/mobv3_mosquitto_server_key:ro

[Service]
LoadCredentialEncrypted=mobv3_mosquitto_server_key:$CREDENTIAL_DIR/mobv3_mosquitto_server_key.cred
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF

log "Generated Mosquitto env and Quadlet unit"
