#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/../lib/config.sh"

load_config machine
require_machine_config
require_vars APP_DIR HOST_BIND_IP WORKDIR CERT_DIR CREDENTIAL_DIR GO_IMAGE TARGETARCH MQTT_PROTOCOL MQTT_PORT PROXY_PORT USB_PRINTER QRPROXY_MQTT_CLIENT_ID QTERM_MQTT_TOPIC
prepare_outputs

source_dir="$APP_DIR/source"

cat >"$env_out/qrproxy.env" <<EOF
# Generated by deploy/services/qrproxy.sh. Do not edit by hand.
PROXY_IP=0.0.0.0
PROXY_PORT=$PROXY_PORT
USB_PRINTER=$USB_PRINTER
MQTT_PROTOCOL=$MQTT_PROTOCOL
MQTT_HOST=mobv3_mosquitto_broker
MQTT_PORT=$MQTT_PORT
QRPROXY_MQTT_CLIENT_ID=$QRPROXY_MQTT_CLIENT_ID
QTERM_MQTT_TOPIC=$QTERM_MQTT_TOPIC
TLS_CA_PATH=$WORKDIR/certs/ca.crt
TLS_CLIENT_CERT_PATH=$WORKDIR/certs/client.crt
TLS_CLIENT_KEY_PATH=/run/secrets/mobv3_client_key
EOF

cat >"$quadlet_out/mobv3-qrproxy.build" <<EOF
[Build]
ImageTag=localhost/mobv3-qrproxy:latest
File=$source_dir/cmd/qrproxy/Containerfile
SetWorkingDirectory=$source_dir
BuildArg=GO_IMAGE=$GO_IMAGE
BuildArg=TARGETARCH=$TARGETARCH
EOF

cat >"$quadlet_out/mobv3-qrproxy.container" <<EOF
[Unit]
Description=MOBv3 QRProxy
Wants=network-online.target mobv3-mosquitto.service
After=network-online.target mobv3-mosquitto.service

[Container]
ContainerName=mobv3_qrproxy
Image=mobv3-qrproxy.build
User=0:0
GroupAdd=keep-groups
SecurityLabelDisable=true
EnvironmentFile=$APP_DIR/deploy/generated/env/qrproxy.env
Network=mobv3.network
PublishPort=$HOST_BIND_IP:$PROXY_PORT:$PROXY_PORT
Volume=$CERT_DIR/ca.crt:$WORKDIR/certs/ca.crt:ro,Z
Volume=$CERT_DIR/client.crt:$WORKDIR/certs/client.crt:ro,Z
Volume=\${CREDENTIALS_DIRECTORY}/mobv3_client_key:/run/secrets/mobv3_client_key:ro
AddDevice=$USB_PRINTER:$USB_PRINTER

[Service]
LoadCredentialEncrypted=mobv3_client_key:$CREDENTIAL_DIR/mobv3_client_key.cred
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
EOF

log "Generated QRProxy env and Quadlet units"
